# Generated by Django 3.2 on 2021-04-15 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_fruit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vegetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_Vegetable', models.CharField(max_length=255)),
                ('price_Vegetable', models.FloatField()),
                ('stock_Vegetable', models.IntegerField()),
                ('image_url_Vegetable', models.CharField(max_length=2083)),
            ],
        ),
    ]
